name: Update list
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["pypy3.9", "pypy3.10", "3.9", "3.10", "3.11", "3.12"]
    permissions:
      contents: write
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - name: Check out repository code
        uses: actions/checkout@v4

      # Other steps that change files in the repository
      - uses: actions/setup-python@v5
      - run: python -m pip install --upgrade pip requests bs4
      - run: python get_oci_ips_.py
      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5



